---  # vim:se ft=yaml.ansible:
- name: Set up user's git config
  ansible.builtin.copy:
    src: "gitignore"
    dest: "~/.gitignore"
    owner: anxolerd
    group: anxolerd
    mode: "0640"

- name: Set up user's git config
  git_config:
    name: "{{ item.key }}"
    scope: global
    value: "{{ item.value }}"
  with_dict: "{{ git_options }}"
