---  # vim: set ft=yaml.ansible :
- name: Configure i3blocks
  block:

    - name: Ensure configuration directory exists
      file:
        path: ~/.config/i3blocks
        state: directory
        owner: anxolerd
        group: anxolerd
        mode: "0755"

    - name: Create i3blocks config file
      template:
        src: i3blocks.config.j2
        dest: ~/.config/i3blocks/config
        owner: anxolerd
        group: anxolerd
        mode: "0640"

- name: Configure i3
  block:

    - name: Ensure configuration directory exists
      file:
        path: ~/.config/i3
        state: directory
        owner: anxolerd
        group: anxolerd
        mode: "0755"

    - name: Download theme file
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/catppuccin/i3/main/themes/catppuccin-{{ catppuccin.theme }}"
        dest: "~/.config/i3/catppuccin-{{ catppuccin.theme }}"
        owner: anxolerd
        group: anxolerd
        mode: 0640

    - name: Create i3 config file
      template:
        src: i3gaps.config.j2
        dest: ~/.config/i3/config
        owner: anxolerd
        group: anxolerd
        mode: "0640"

- name: Configure rofi launcher
  block:
    - name: Create configuration directories
      ansible.builtin.file:
        path: "{{ dir.path }}"
        state: directory
        owner: anxolerd
        group: anxolerd
        mode: "0755"
      loop:
        - path: ~/.config/rofi
          label: configuration
        - path: ~/.local/share/rofi/themes
          label: themes
      loop_control:
        loop_var: dir
        label: "{{ dir.label }}"

    - name: Download theme file
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/catppuccin/rofi/main/basic/.local/share/rofi/themes/catppuccin-{{ catppuccin.theme }}.rasi
        dest: ~/.local/share/rofi/themes/catppuccin-{{ catppuccin.theme }}.rasi
        owner: anxolerd
        group: anxolerd
        mode: 0640

    - name: Configure rofi launcher
      ansible.builtin.template:
        src: config.rasi.j2
        dest: ~/.config/rofi/config.rasi
        owner: anxolerd
        group: anxolerd
        mode: "0640"
