---  # vim:se ft=yaml.ansible:
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Ensure that Bash is configured
  ansible.builtin.import_tasks: bash.yml

- name: Ensure that SSH is configured
  ansible.builtin.import_tasks: ssh.yml

- name: Ensure that Git is configured
  ansible.builtin.import_tasks: git.yml

- name: Ensure X is configured
  ansible.builtin.import_tasks: X.yml

- name: Ensure i3 is configured
  ansible.builtin.import_tasks: i3.yml
  when: >-
    'i3-gaps' in ansible_facts.packages
    or 'i3' in ansible_facts.packages

- name: Ensure that Alacritty is configured
  ansible.builtin.import_tasks: alacritty.yml
  when: "'alacritty' in ansible_facts.packages"

- name: Ensure that Bat is configured
  ansible.builtin.import_tasks: bat.yml
  when: "'bat' in ansible_facts.packages"

- name: Ensure that Vim is configured
  ansible.builtin.import_tasks: vim.yml
  when: "'vim' in ansible_facts.packages"

- name: Ensure that Tmux is configured
  ansible.builtin.import_tasks: tmux.yml
  when: "'tmux' in ansible_facts.packages"

- name: Ensure that Kubectl is configured
  ansible.builtin.import_tasks: kubectl.yml
  when: "'kubectl' in ansible_facts.packages"

- name: Configure user periodic tasks
  ansible.builtin.import_tasks: systemd.yml
