---
- name: foo
  hosts: localhost
  vars:
    memberships:
      - group: docker
        users: ['u1', 'u2', 'u3']
        required_package: 'docker'
      - group: libvirt
        users: ['u1', 'u3']
        required_pacakge: 'virt-manager'
  tasks:

  - name: print message
    debug:
      msg: "{{ memberships | subelements('users') | map('reverse') }}"
