---
services_safe_restart:
  - acpid
  - bluetooth
  - bluetooth-mesh
  - irqbalance
  - lm_sensors
  - NetworkManager
  - cups  # CUPS
  - cups-browsed  # CUPS network printers

services_unsafe_restart:
  - docker
  - lightdm  # LightDM
