---
services_safe_restart:
  - service: acpid
    provided_by: acpid
  - service: bluetooth
    provided_by: bluez
  - service: bumblebee
    provided_by: bumblebee
  - service: NetworkManager
    provided_by: networkmanager
  - service: iwd
    provided_by: iwd
  - service: chronyd  # NTP client
    provided_by: chrony
  - service: cupsd  # CUPS
    provided_by: cups
  - service: cups-browsed  # CUPS network printers
    provided_by: cups

services_unsafe_restart:
  - service: docker
    provided_by: docker
  - service: display-manager  # LightDM
    provided_by: display-manager-init
  - service: libvirtd
    provided_by: libvirt
