---
services_safe_restart:
  - acpid
  - bluetooth
  - bumblebee
  - NetworkManager
  - cupsd  # CUPS
  - cups-browsed  # CUPS network printers

services_unsafe_restart:
  - docker
  - display-manager  # LightDM
