---
- name: Enable and start services
  listen: ensure-services-started
  service:
    name: "{{ item }}"
    enabled: true
    runlevel: default
    state: started
  register: start_srv
  failed_when: "start_srv.failed and 'Service is in unknown state' not in start_srv.msg"
  with_items: "{{ services_safe_restart + services_unsafe_restart }}"

- name: Reload services
  listen: ensure-services-reloaded
  systemd:
    name: "{{ item }}"
    state: reloaded-or-restarted
  register: start_srv
  failed_when: "start_srv.failed and 'Service is in unknown state' not in start_srv.msg"
  with_items: "{{ services_safe_restart }}"

- name: Reload and apply udev rules from configs
  listen: update-udev-rules
  shell: udevadm control --reload-rules && udevadm trigger
